
os:
  - linux

language: c

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install gcovr

install:
  - ./scripts/travis_install.sh

script:
  - cd src
  - make GCOV=1

after_success:
  - coveralls --root . --exclude doc --exclude scripts --exclude test --gcov-options '\-lp'

sudo: required

addons:
  coverity_scan:
    project:
      name: "pchero/jade"
    notification_email: pchero21@gmail.com
